### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by mariohackandglitch** [andibadra/unFARC#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'DynamicFileByteProvider' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\glo.cs	225	Active
Error	CS0246	The type or namespace name 'Be' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\frame\MessageView.Designer.cs	279	Active
Error	CS0246	The type or namespace name 'FastColoredTextBoxNS' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\frame\MessageView.Designer.cs	282	Active
Error	CS0246	The type or namespace name 'Be' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\glo.cs	7	Active
Error	CS0246	The type or namespace name 'HexBox' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\glo.cs	218	Active
Error	CS0246	The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\MainForm.cs	11	Active
Error	CS0246	The type or namespace name 'LibEveryFileExplorer' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	8	Active
Error	CS0246	The type or namespace name 'LibEveryFileExplorer' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	9	Active
Error	CS0246	The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\Program.cs	6	Active
Error	CS0246	The type or namespace name 'Be' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\frame\MessageView.Designer.cs	36	Active
Error	CS0246	The type or namespace name 'FastColoredTextBoxNS' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\frame\MessageView.Designer.cs	39	Active
Error	CS0246	The type or namespace name 'FastColoredTextBoxNS' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\frame\MessageView.Designer.cs	168	Active
Error		Invalid Resx file. Could not load type FastColoredTextBoxNS.ServiceColors, FastColoredTextBox, Version=2.16.11.0, Culture=neutral, PublicKeyToken=fb8aa12b994ef61b which is used in the .RESX file.  Ensure that the necessary references have been added to your project. Line 137, position 5.	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\frame\MessageView.resx	137	
Error	CS0246	The type or namespace name 'DynamicFileByteProvider' could not be found (are you missing a using directive or an assembly reference?)	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\glo.cs	221	Active
Error	CS0103	The name 'JsonConvert' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\MainForm.cs	234	Active
Error	CS0103	The name 'Formatting' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\MainForm.cs	234	Active
Error	CS0103	The name 'Ionic' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\MainForm.cs	298	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	94	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	95	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	96	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	97	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	122	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	123	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	124	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	125	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	149	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	150	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	151	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	152	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	172	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	173	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	174	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	175	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	195	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	196	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	197	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	198	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	222	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	227	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	246	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	251	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	270	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	274	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	293	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	298	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	317	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	322	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	342	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	346	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	366	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	371	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	392	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	395	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	438	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	438	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	443	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	443	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	534	Active
Error	CS0103	The name 'GFXUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	534	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	534	Active
Error	CS0103	The name 'ColorFormat' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	534	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	568	Active
Error	CS0103	The name 'IOUtil' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	581	Active
Error	CS0103	The name 'ETC1' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\meta\Textures.cs	581	Active
Error	CS0103	The name 'JsonConvert' does not exist in the current context	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\Program.cs	22	Active
Warning		The referenced component 'FastColoredTextBox' could not be found.	unFARC			
Warning		Could not resolve this reference. Could not locate the assembly "Ionic.Zlib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	unFARC			
Warning		Could not resolve this reference. Could not locate the assembly "LibEveryFileExplorer". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	unFARC			
Warning		Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	unFARC			
Warning		Could not resolve this reference. Could not locate the assembly "Be.Windows.Forms.HexBox". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	unFARC			
Warning		The referenced component 'Ionic.Zlib' could not be found.	unFARC			
Warning		The referenced component 'Be.Windows.Forms.HexBox' could not be found.	unFARC			
Warning		Could not resolve this reference. Could not locate the assembly "FastColoredTextBox". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	unFARC			
Warning		The referenced component 'LibEveryFileExplorer' could not be found.	unFARC			
Warning		The referenced component 'Newtonsoft.Json' could not be found.	unFARC			
Warning	CS0168	The variable 'exception' is declared but never used	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\archive\FARC.cs	84	Active
Warning	CS0168	The variable 'exception' is declared but never used	unFARC	C:\Users\PC\Desktop\carpetas\cosas\nds hack\3dshack\psmd\unfarc\unFARC\unFARC\archive\SIR0.cs	92	Active

**Comment by mariohackandglitch** [comment]
Would it be possible to make a compiled release? :P

**Comment by andibadra** [comment]
You should re-point references to assembly on ./Library/ path (since is not installed on GAC) and then build. Actually i already shared compiled on pp.org forum :P 

if you lazy to search on pp.org forum, you can download [unFARC_Debug.zip](https://github.com/andibadra/unFARC/files/455255/unFARC_Debug.zip). this file compiled from this repository so is not up to date.

**Comment by mariohackandglitch** [comment]
I saw it in pp.org, the problem is that dropbox link is broken (404)

**Comment by mariohackandglitch** [comment]
Anyway, I managed to compile it, thanks ;)
